sudo: required
dist: trusty
services:
  — docker
before_install:
— docker pull blang/latex:ubuntu
— docker run -v "$PWD":/data blang/latex:ubuntu /bin/sh -c "cd /data; pwd;"
— docker ps -a
# — docker run blang/latex:ubuntu /bin/sh -c "cd /root/sinatra; bundle exec rake test"
script: 
  # — wget https://raw.githubusercontent.com/blang/latex-docker/master/latexdockercmd.sh

  — chmod +x latexdockercmd.sh 

  — pwd

  — ls -hla ./thesis_zhen

  — mkdir _build

  — ls -hla

  # — "./latexdockercmd.sh pdflatex " 
deploy:
  provider: releases
  file: "./_build/thesis_zhen.pdf"
  on:
    repo: zhenyisx/paper
  skip_cleanup: 'true'
