sudo: required 
dist: trusty 
services:
  — docker 
before_install: 
  — docker pull blang/latex:ubuntu 
  — docker run -v "$PWD":/data blang/latex:ubuntu /bin/bash -c "cd /data; latexmk -xelatex -interaction=nonstopmode -halt-on-error ./thesis_zhen/thesis_zhen.tex -outdir=./_build;"  
script: 
  — pwd 
  — tree . 
deploy:
  provider: releases
  file: "./_build/thesis_zhen.pdf"
  on:
    repo: zhenyisx/paper
  skip_cleanup: 'true'

